import networkx as nx
from ..utils import places


def gerarGrafo():
    G = nx.Graph()

    for place in places:
        G.add_node(place)

    G.add_edge("Reator", "Turbina Superior", peso=0)
    G.add_edge("Reator", "Turbina Inferior", peso=0)
    G.add_edge("Reator", "Reator", peso=0)
    G.add_edge("Turbina Inferior", "Turbina Superior", peso=0)
    G.add_edge("Turbina Inferior", "Reator", peso=0)
    G.add_edge("Turbina Inferior", "Elétrica", peso=0)
    G.add_edge("Turbina Inferior", "Armazem", peso=0)
    G.add_edge("Turbina Inferior", "Turbina Inferior", peso=0)
    G.add_edge("Turbina Superior", "Turbina Inferior", peso=0)
    G.add_edge("Turbina Superior", "Reator", peso=0)
    G.add_edge("Turbina Superior", "Ala médica", peso=0)
    G.add_edge("Turbina Superior", "Cafeteria", peso=0)
    G.add_edge("Turbina Superior", "Turbina Superior", peso=0)
    G.add_edge("Ala médica", "Cafeteria", peso=0)
    G.add_edge("Ala médica", "Turbina Superior", peso=0)
    G.add_edge("Ala médica", "Ala médica", peso=0)
    G.add_edge("Elétrica", "Turbina Inferior", peso=0)
    G.add_edge("Elétrica", "Armazem", peso=0)
    G.add_edge("Elétrica", "Elétrica", peso=0)
    G.add_edge("Armazem", "Turbina Inferior", peso=0)
    G.add_edge("Armazem", "Escudos", peso=0)
    G.add_edge("Armazem", "Admin", peso=0)
    G.add_edge("Armazem", "Cafeteria", peso=0)
    G.add_edge("Armazem", "Elétrica", peso=0)
    G.add_edge("Armazem", "Armazem", peso=0)
    G.add_edge("Cafeteria", "Armazem", peso=0)
    G.add_edge("Cafeteria", "Ala médica", peso=0)
    G.add_edge("Cafeteria", "Turbina Superior", peso=0)
    G.add_edge("Cafeteria", "Admin", peso=0)
    G.add_edge("Cafeteria", "Armas", peso=0)
    G.add_edge("Cafeteria", "Cafeteria", peso=0)
    G.add_edge("Admin", "Admin", peso=0)
    G.add_edge("Admin", "Cafeteria", peso=0)
    G.add_edge("Admin", "Armazem", peso=0)
    G.add_edge("Escudos", "Armazem", peso=0)
    G.add_edge("Escudos", "Navegação", peso=0)
    G.add_edge("Escudos", "Escudos", peso=0)
    G.add_edge("Escudos", "O2", peso=0)
    G.add_edge("Escudos", "Armas", peso=0)
    G.add_edge("Navegação", "Navegação", peso=0)
    G.add_edge("Navegação", "Escudos", peso=0)
    G.add_edge("Navegação", "O2", peso=0)
    G.add_edge("Navegação", "Armas", peso=0)
    G.add_edge("Armas", "Navegação", peso=0)
    G.add_edge("Armas", "Armas", peso=0)
    G.add_edge("Armas", "Escudos", peso=0)
    G.add_edge("Armas", "O2", peso=0)
    G.add_edge("Armas", "Cafeteria", peso=0)
    G.add_edge("O2", "O2", peso=0)
    G.add_edge("O2", "Armas", peso=0)
    G.add_edge("O2", "Navegação", peso=0)
    G.add_edge("O2", "Escudos", peso=0)

    return G
