import networkx as nx
from ..utils import places


def gerarGrafo():
    G = nx.Graph()

    for place in places:
        G.add_node(place)

    G.add_edge("Reator", "Turbina Superior", peso=4.2)
    G.add_edge("Reator", "Turbina Inferior", peso=4.2)
    G.add_edge("Reator", "Reator", peso=2)
    G.add_edge("Turbina Inferior", "Turbina Superior", peso=5)
    G.add_edge("Turbina Inferior", "Reator", peso=4.2)
    G.add_edge("Turbina Inferior", "Elétrica", peso=4.5)
    G.add_edge("Turbina Inferior", "Armazem", peso=4.8)
    G.add_edge("Turbina Inferior", "Turbina Inferior", peso=1.3)
    G.add_edge("Turbina Superior", "Turbina Inferior", peso=5)
    G.add_edge("Turbina Superior", "Reator", peso=4.2)
    G.add_edge("Turbina Superior", "Ala médica", peso=3.3)
    G.add_edge("Turbina Superior", "Cafeteria", peso=3.6)
    G.add_edge("Turbina Superior", "Turbina Superior", peso=1.3)
    G.add_edge("Ala médica", "Cafeteria", peso=3.7)
    G.add_edge("Ala médica", "Turbina Superior", peso=3.3)
    G.add_edge("Ala médica", "Ala médica", peso=2)
    G.add_edge("Elétrica", "Turbina Inferior", peso=4.5)
    G.add_edge("Elétrica", "Armazem", peso=2.9)
    G.add_edge("Elétrica", "Elétrica", peso=2)
    G.add_edge("Armazem", "Turbina Inferior", peso=4.8)
    G.add_edge("Armazem", "Escudos", peso=3.6)
    G.add_edge("Armazem", "Admin", peso=1.8)
    G.add_edge("Armazem", "Cafeteria", peso=3.3)
    G.add_edge("Armazem", "Elétrica", peso=2.9)
    G.add_edge("Armazem", "Armazem", peso=4)
    G.add_edge("Cafeteria", "Armazem", peso=3.3)
    G.add_edge("Cafeteria", "Ala médica", peso=3.7)
    G.add_edge("Cafeteria", "Turbina Superior", peso=3.6)
    G.add_edge("Cafeteria", "Admin", peso=2.2)
    G.add_edge("Cafeteria", "Armas", peso=2.4)
    G.add_edge("Cafeteria", "Cafeteria", peso=5)
    G.add_edge("Admin", "Admin", peso=2)
    G.add_edge("Admin", "Cafeteria", peso=2.2)
    G.add_edge("Admin", "Armazem", peso=1.8)
    G.add_edge("Escudos", "Armazem", peso=3.6)
    G.add_edge("Escudos", "Navegação", peso=4.3)
    G.add_edge("Escudos", "Escudos", peso=1)
    G.add_edge("Escudos", "O2", peso=5.45)
    G.add_edge("Escudos", "Armas", peso=5.9)
    G.add_edge("Navegação", "Navegação", peso=1.4)
    G.add_edge("Navegação", "Escudos", peso=4.3)
    G.add_edge("Navegação", "O2", peso=3.2)
    G.add_edge("Navegação", "Armas", peso=4.75)
    G.add_edge("Armas", "Navegação", peso=4.75)
    G.add_edge("Armas", "Armas", peso=1)
    G.add_edge("Armas", "Escudos", peso=5.9)
    G.add_edge("Armas", "O2", peso=2.5)
    G.add_edge("Armas", "Cafeteria", peso=2.4)
    G.add_edge("O2", "O2", peso=1.4)
    G.add_edge("O2", "Armas", peso=2.5)
    G.add_edge("O2", "Navegação", peso=3.2)
    G.add_edge("O2", "Escudos", peso=5.45)
    return G
