tasks = {"Acabar com os Asteroides": {"local": "", "tempo": 0},
         "Ajustar a Potência do Motor": {"local": "", "tempo": 0},
         "Arrumar Fiação": {"local": "", "tempo": 0},
         "Calibrar o Distribuidor": {"local": "", "tempo": 0},
         "Desviar a Energia para Sala": {"local": "", "tempo": 0},
         "Desbloquear Colectores": {"local": "", "tempo": 0},
         "Esvaziar Escotilha": {"local": "", "tempo": 0},
         "Esvaziar o Lixo": {"local": "", "tempo": 0},
         "Encher os Motores": {"local": "", "tempo": 0},
         "Estabilizar a Direção": {"local": "", "tempo": 0},
         "Enviar Scan": {"local": "", "tempo": 0},
         "Ligar Reator": {"local": "", "tempo": 0},
         "Limpe o Filtro do O2": {"local": "", "tempo": 0},
         "Inspecionar Amostra": {"local": "", "tempo": 0},
         "Mapear Rota": {"local": "", "tempo": 0},
         "Passar o Cartão": {"local": "", "tempo": 0},
         "Reativar Escudos": {"local": "", "tempo": 0},
         "Transferir Dados": {"local": "", "tempo": 0}}


places = {"Cafeteria": {"x": 0, "y": 0},
          "Armas": {"x": 0, "y": 0},
          "O2": {"x": 0, "y": 0},
          "Navegação": {"x": 0, "y": 0},
          "Escudos": {"x": 0, "y": 0},
          "Comunicação": {"x": 0, "y": 0},
          "Armazem": {"x": 0, "y": 0},
          "Admin": {"x": 0, "y": 0},
          "Elétrica": {"x": 0, "y": 0},
          "Reator": {"x": 0, "y": 0},
          "Ala médica": {"x": 0, "y": 0},
          "Segurança": {"x": 0, "y": 0},
          "Turbina Superior": {"x": 0, "y": 0},
          "Turbina Inferior": {"x": 0, "y": 0}
          }
